# DigitalOcean datacenter region slug (str).
# Full detail here: https://docs.digitalocean.com/platform/regional-availability/
digitalocean_region: nyc2

# List of (int) protected droplets IDs.
# You can't stop/delete a protected droplet.
# You can't detach a volume from a protected droplet.
protected_droplets: [
  463310454, # stg-cloutfit
]

# List of (str) protected volumes IDs.
# You can't delete a protected volume.
protected_volumes: [
  "5cebc54e-dac1-11ef-b1a6-0a58ac140025", # models01
]

# JSON indentation level (int) for raw outputs.
json_indent: 4

# Action ping interval (float) in seconds.
ping_interval: 1
