#cloud-config
package_update: true
packages:
  - git
  - python3
  - python3-venv
  - python3-pip
  - tree
  - htop
  - libgl1

mounts:
  - [ "/dev/disk/by-id/scsi-0DO_Volume_models01", "/mnt", "ext4", "defaults,nofail,discard", "0", "0" ]

write_files:
  # Add the setup_venv.sh script to the /app directory
  - path: /usr/local/bin/setup_venv.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      cd /app/generative-models
      python3 -m venv .pt2
      source .pt2/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements/pt2.txt
      echo "-------------------------------------"
      echo "Updating CUDA to 1.21 for nvidia H100"
      echo "-------------------------------------"
      python3 -m pip uninstall -y torch torchvision torchaudio torchdata xformers
      python3 -m pip install --index-url https://download.pytorch.org/whl/cu121 torch torchvision torchaudio torchdata xformers
      deactivate
  
  # Add the run_simple_video_sample.sh script to the /usr/local/bin directory 
  - path: /usr/local/bin/run_simple_video_sample.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      cd /app/generative-models
      source .pt2/bin/activate
      IMAGES_DIR="/mnt/assets/images"
      for version in sv3d_u sv3d_p; do
        for filepath in $(ls -1 $IMAGES_DIR); do
          filename=$(basename $filepath)
          output_folder="outputs/${HOSTNAME}/${version}/${filename//./_}"
          echo
          echo "================================================================================="
          echo "Generating video $version for $filepath"
          echo "================================================================================="
          python3 scripts/sampling/simple_video_sample.py \
            --input_path $filepath \
            --version $version \
            --output_folder $output_folder
        done
      done
      deactivate

runcmd:
  # Create the /app directory
  - mkdir -p /app

  # Clone the repository from Stability AI
  - git clone https://github.com/Stability-AI/generative-models /app/generative-models

  # Ping numpy version
  - sed -i 's/numpy>=1.24.4/numpy==1.24.4/' /app/generative-models/requirements/pt2.txt

  # Add missing packages
  - echo "onnxruntime==1.20.1" >> /app/generative-models/requirements/pt2.txt
  - echo "imageio==2.37.0" >> /app/generative-models/requirements/pt2.txt
  - echo "imageio-ffmpeg==0.6.0" >> /app/generative-models/requirements/pt2.txt

  # Create symbolic links to the mounted volume
  - ln -s /mnt/stability-ai/generative-models/checkpoints /app/generative-models/checkpoints
  - ln -s /mnt/stability-ai/generative-models/outputs /app/generative-models/outputs

  # Setup the Python virtual environment
  - /usr/local/bin/setup_venv.sh

  # Run the simple video sample script
  - /usr/local/bin/run_simple_video_sample.sh