#cloud-config
package_update: true
packages:
  - git
  - python3
  - python3-venv
  - python3-pip
  - tree
  - htop
  - libgl1
  - ffmpeg
  - wget

mounts:
  - [ "/dev/disk/by-id/scsi-0DO_Volume_models02", "/mnt", "ext4", "defaults,nofail,discard", "0", "0" ]

write_files:
  # Download ComfyUI and create symbolic links to the models
  - path: /app/download_comfy.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "--------------------------------------------------------"
      echo "Clone ComfyUI and create symbolic links"
      echo "--------------------------------------------------------"
      git clone https://github.com/comfyanonymous/ComfyUI /app/ComfyUI

      function create_symlink {
          local dir="$1"

          rm -rf /app/ComfyUI/$dir
          ln -s /mnt/comfy/$dir /app/ComfyUI/$dir
      }

      # Create symbolic links to the models
      create_symlink "models/checkpoints"
      create_symlink "models/clip_vision"
      create_symlink "models/diffusion_models"
      create_symlink "models/loras"
      create_symlink "models/text_encoders"
      create_symlink "models/vae"

      # Create symbolic links to the output directory
      create_symlink "output"

  # Create the virtual environment
  - path: /app/create_env.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "--------------------------------------------------------"
      echo "Creating virtual environment"
      echo "--------------------------------------------------------"
      cd /app/ComfyUI
      python3 -m venv .env
      source .env/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
      python3 -m pip install -r requirements.txt

  # Install custom nodes
  - path: /app/install_custom_nodes.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "---------------------------------------"
      echo "Install custom nodes"
      echo "---------------------------------------"
      cd /app/ComfyUI
      source .env/bin/activate
      
      # ComfyUI-Manager
      echo ">>> Install ComfyUI-Manager"
      cd /app/ComfyUI/custom_nodes/
      git clone https://github.com/ltdrdata/ComfyUI-Manager
      cd ComfyUI-Manager
      python3 -m pip install -r requirements.txt
      python3 -m pip install uv # missing package, don't know why
      
      # ComfyUI-KJNodes
      echo ">>> Install ComfyUI-KJNodes"
      cd /app/ComfyUI/custom_nodes/
      git clone https://github.com/kijai/ComfyUI-KJNodes.git
      cd ComfyUI-KJNodes
      python3 -m pip install -r requirements.txt
      
      # ComfyUI-VideoHelperSuite
      echo ">>> Install ComfyUI-VideoHelperSuite"
      cd /app/ComfyUI/custom_nodes/
      git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git
      cd ComfyUI-VideoHelperSuite
      python3 -m pip install -r requirements.txt

  # Run comfy
  - path: /app/run_comfy.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      COMFY_IP=$(curl -s ifconfig.me)
      COMFY_PORT=5000
      COMFY_VERSION=$(grep '__version__' /app/ComfyUI/comfyui_version.py | sed -E 's/__version__ = "(.*)"/\1/')
      echo "--------------------------------------------------------"
      echo "Running ComfyUI v${COMFY_VERSION} from master"
      echo
      echo "Open http://${COMFY_IP}:${COMFY_PORT} in your browser"
      echo "--------------------------------------------------------"
      cd /app/ComfyUI
      source .env/bin/activate
      python3 main.py --listen=0.0.0.0 --port=$COMFY_PORT

runcmd:
  # Launch comfy
  - /app/download_comfy.sh
  - /app/create_env.sh
  - /app/install_custom_nodes.sh
  - /app/run_comfy.sh