#cloud-config
package_update: true
packages:
  - git
  - python3
  - python3-venv
  - python3-pip
  - tree
  - libgl1
  - ffmpeg

mounts:
  - [ "/dev/disk/by-id/scsi-0DO_Volume_models02", "/mnt", "ext4", "defaults,nofail,discard", "0", "0" ]

write_files:
  # Sytemd service to collect logs before unmounting /mnt
  - path: /etc/systemd/system/shutdown-log.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Collect logs before unmounting /mnt
      DefaultDependencies=no
      Before=umount.target
      After=final.target
      RequiresMountsFor=/mnt

      [Service]
      Type=oneshot
      ExecStart=/app/shutdown_log.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

  # Script to collect logs before unmounting /mnt
  - path: /app/shutdown_log.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      LOG_FILE="/var/log/cloud-init-output.log"
      DEST_DIR="/app/ComfyUI/output/"
      cp $LOG_FILE $DEST_DIR

  # Download ComfyUI and create symbolic links to the models
  - path: /app/download_comfy.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "--------------------------------------------------------"
      echo "Clone ComfyUI and configure the workspace"
      echo "--------------------------------------------------------"
      git clone https://github.com/comfyanonymous/ComfyUI /app/ComfyUI

      function create_symlink {
          local src="$1"
          local dst="${2:-$1}"

          rm -rf /app/ComfyUI/$dst
          ln -s /mnt/comfy/$src /app/ComfyUI/$dst
      }

      function create_output_dir {
          local output_dir="output/$(date '+%Y-%m-%d_%H-%M-%S')"

          mkdir -p /mnt/comfy/$output_dir
          echo $output_dir
      }

      echo "Creating symbolic links to the models"
      create_symlink "models/checkpoints"
      create_symlink "models/clip_vision"
      create_symlink "models/diffusion_models"
      create_symlink "models/loras"
      create_symlink "models/text_encoders"
      create_symlink "models/vae"

      OUTPUT_DIR=$(create_output_dir)
      echo "Creating symbolic link to the output dir /mnt/comfy/$OUTPUT_DIR"
      create_symlink "$OUTPUT_DIR" "output"

      # https://www.youtube.com/watch?v=cmikc-Jo1gk
      # https://www.youtube.com/watch?v=Xsx-u0OMezw
      echo "Downloading Art Styles csv file with 300 prompt styles"
      wget --quiet -c 'https://drive.usercontent.google.com/u/0/uc?id=1A_4-FbTyJA8TtURr7wNxtNwZI0KnKInW&export=download' -O /app/ComfyUI/styles.csv

      echo "All set!"

  # Create the virtual environment
  - path: /app/create_env.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "--------------------------------------------------------"
      echo "Creating virtual environment"
      echo "--------------------------------------------------------"
      cd /app/ComfyUI
      python3 -m venv .env
      source .env/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
      python3 -m pip install -r requirements.txt

  # Install custom nodes
  - path: /app/install_custom_nodes.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "---------------------------------------"
      echo "Install custom nodes"
      echo "---------------------------------------"
      cd /app/ComfyUI
      source .env/bin/activate

      function install_custom_node {
          local repo_url="$1"
          local name="$2"
          local extra_packages="$3"

          echo 
          echo ">>> Installing custom node from $repo_url"

          cd /app/ComfyUI/custom_nodes/
          git clone $repo_url $name
          cd $name

          if [ -f "requirements.txt" ]; then
              python3 -m pip install -r requirements.txt
          fi

          if [ -n "$extra_packages" ]; then
              python3 -m pip install $extra_packages
          fi
      }

      install_custom_node https://github.com/ltdrdata/ComfyUI-Manager.git "ComfyUI-Manager" "uv"
      install_custom_node https://github.com/yolain/ComfyUI-Easy-Use.git "ComfyUI-Easy-Use"
      install_custom_node https://github.com/kijai/ComfyUI-KJNodes.git "ComfyUI-KJNodes"
      install_custom_node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git "ComfyUI-VideoHelperSuite"
      install_custom_node https://github.com/theUpsider/ComfyUI-Styles_CSV_Loader.git "ComfyUI-Styles_CSV_Loader"
      install_custom_node https://github.com/WASasquatch/was-node-suite-comfyui.git "ComfyUI-Was-Node-Suite"

  # Run comfy
  - path: /app/run_comfy.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      COMFY_IP=$(curl -s ifconfig.me)
      COMFY_PORT=5000
      COMFY_VERSION=$(grep '__version__' /app/ComfyUI/comfyui_version.py | sed -E 's/__version__ = "(.*)"/\1/')
      echo
      echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      echo
      echo '   ______                ____      __  ______'
      echo '  / ____/___  ____ ___  / __/_  __/ / / /  _/'
      echo ' / /   / __ \/ __ `__ \/ /_/ / / / / / // /  '
      echo '/ /___/ /_/ / / / / / / __/ /_/ / /_/ // /   '
      echo '\____/\____/_/ /_/ /_/_/  \__, /\____/___/   '
      echo '                         /____/              '
      echo
      echo "Running ComfyUI v${COMFY_VERSION} from master"
      echo
      echo "Open http://${COMFY_IP}:${COMFY_PORT} in your browser"
      echo
      echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      echo
      cd /app/ComfyUI
      source .env/bin/activate
      python3 main.py --listen=0.0.0.0 --port=$COMFY_PORT

runcmd:
  - systemctl daemon-reload
  - systemctl enable shutdown-log.service
  - /app/download_comfy.sh
  - /app/create_env.sh
  - /app/install_custom_nodes.sh
  - /app/run_comfy.sh