#cloud-config
package_update: true
packages:
  - git
  - tree
  - htop
  - wget

mounts:
  - [ "/dev/disk/by-id/scsi-0DO_Volume_models02", "/mnt", "ext4", "defaults,nofail,discard", "0", "0" ]

write_files:
  # Create the base directories
  - path: /app/create_base_dirs.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "---------------------------------------"
      echo "Create base dirs in /mnt"
      echo "---------------------------------------"
      mkdir -p /mnt/comfy/models
      mkdir -p /mnt/comfy/ouput
      echo "All set!"

  # Download the files
  - path: /app/downloader.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "---------------------------------------"
      echo "Downloading files"
      echo "---------------------------------------"
      BASE_DIR="/mnt/comfy"
      FILES_LIST="/app/files_list.txt"
      cd $BASE_DIR
      while read -r URL DEST_DIR; do
          # Skip empty lines and lines that start with #
          [[ -z "$URL" || "$URL" =~ ^# ]] && continue

          FILE_NAME=$(basename "$URL")
          FILE_PATH="$DEST_DIR$FILE_NAME" # DEST_DIR has / at the end

          if [ -f "$FILE_PATH" ]; then
              echo "--- Skipping $FILE_PATH (already exists)"
          else
              echo ">>> Downloading $FILE_PATH"
              mkdir -p "$DEST_DIR"
              wget --quiet -c "$URL" -P "$DEST_DIR"
          fi
      done < $FILES_LIST
      echo "---------------------------------------"
      echo "All files downloaded!"
      echo "---------------------------------------"
      tree
      echo
      echo "Disk usage:"
      du -sh /mnt
      echo
      echo "Files in models dir:"
      ls -l $BASE_DIR/models/**/*
      echo
      echo "---------------------------------------"
      echo "Downloader script finished!"
      echo "---------------------------------------"
  
  # Write the list of files to download
  - path: /app/files_list.txt
    permissions: '0644'
    content: |
      # ==============================================================================
      # Alert: put / at the end of the destination directory
      # ==============================================================================

      # Cosmos 1.0
      # https://comfyanonymous.github.io/ComfyUI_examples/cosmos/
      #
      https://huggingface.co/comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI/resolve/main/text_encoders/oldt5_xxl_fp8_e4m3fn_scaled.safetensors ./models/text_encoders/
      https://huggingface.co/comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI/resolve/main/vae/cosmos_cv8x8x8_1.0.safetensors ./models/vae/
      https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-7B-Text2World.safetensors ./models/diffusion_models/
      https://huggingface.co/mcmonkey/cosmos-1.0/resolve/main/Cosmos-1_0-Diffusion-7B-Video2World.safetensors ./models/diffusion_models/

      # Flux FP8 version
      # https://comfyanonymous.github.io/ComfyUI_examples/flux/
      #
      https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/flux1-dev-fp8.safetensors ./models/checkpoints/
      https://huggingface.co/Comfy-Org/flux1-schnell/resolve/main/flux1-schnell-fp8.safetensors ./models/checkpoints/
      https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/ae.safetensors ./models/vae/
      https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/resolve/main/flux_realism_lora.safetensors ./models/loras/

      # SDXL ReVision
      # https://comfyanonymous.github.io/ComfyUI_examples/sdxl/
      #
      https://huggingface.co/comfyanonymous/clip_vision_g/resolve/main/clip_vision_g.safetensors ./models/clip_vision/

runcmd:
  - /app/create_base_dirs.sh
  - /app/downloader.sh